@back_cabs_HostAddress = http://localhost:5176

### TEST - CREAR ORDEN CON CLIENTE LEGACY
POST {{back_cabs_HostAddress}}/api/Recepcion
Content-Type: application/json

{
  "nuevoCliente": false,
  "clienteId": 4,
  "citaProgramadaInicio": "2025-10-08T10:00:00",
  "modalidad": "Presencial",
  "tipoOrden": "Asesoria",
  "estado": "CAPTURADA",
  "prioridad": 3,
  "creadoPorUserId": 1
}

### TEST - CREAR ORDEN CON CLIENTE NUEVO
POST {{back_cabs_HostAddress}}/api/Recepcion
Content-Type: application/json

{
  "nuevoCliente": true,
  "nombreCliente": "Nuevo Cliente Test",
  "citaProgramadaInicio": "2025-10-08T14:00:00",
  "modalidad": "Virtual",
  "tipoOrden": "Cotizacion",
  "estado": "CAPTURADA",
  "prioridad": 2,
  "creadoPorUserId": 1
}