### LOGIN
POST http://localhost:5176/api/Auth/login
Content-Type: application/json

{
  "email": "administrador@gmail.com",
  "password": "Admin@123"
}

###

### GET ALL NÚMEROS SERIE - Primera Llamada (CACHE MISS)
GET http://localhost:5176/api/NumeroSerie

###

### GET ALL NÚMEROS SERIE - Segunda Llamada (CACHE HIT)
GET http://localhost:5176/api/NumeroSerie

###

### SEARCH NÚMEROS SERIE - Primera Llamada (CACHE MISS)
GET http://localhost:5176/api/NumeroSerie/search?q=001

###

### SEARCH NÚMEROS SERIE - Segunda Llamada (CACHE HIT)
GET http://localhost:5176/api/NumeroSerie/search?q=001

###
